#ifndef PPM_CONSTANTS_H
#define PPM_CONSTANTS_H

#include <LogicPublicTypes.h>

const U16 MAX_PPM_CHANNELS = 8;
const U16 PRE_PULSE_TIME = 400;
const U16 MIN_FRAME_GAP = 2700;
const U16 MIN_CHANNEL_TIME = 900;
const U16 MAX_CHANNEL_TIME = 2100;
const U16 CENTER_TIME = (MIN_CHANNEL_TIME + MAX_CHANNEL_TIME) / 2;
const U16 TOTAL_FRAME_TIME = 22500;
const U16 FRAME_GAP_TIME = TOTAL_FRAME_TIME - (MAX_PPM_CHANNELS * CENTER_TIME);

#endif // PPM_CONSTANTS_H